(Plfm-909) Use Cloudsearch JAVA SDK instead of HTTP client
Sage-Bionetworks/Synapse-Repository-Services pull request #3214
Opened 2017-12-13 23:07 UTC by zimingd

2017-12-13 23:12 UTC, john-hill commented on lib/lib-auto-generated/src/main/resources/schema/org/sagebionetworks/repo/model/search/Hit.json
> +			"description": "*DEPRECATED* The path of this entity"
Not deprecated.

2017-12-13 23:14 UTC, john-hill commented on lib/lib-search/src/main/java/org/sagebionetworks/search/CloudsSearchDomainClientAdapter.java
> +	private AmazonCloudSearchDomainClient client;
@Autowire

2018-01-15 23:47 UTC, john-hill requested changes

2018-01-15 23:47 UTC, john-hill commented on lib/lib-search/src/main/java/org/sagebionetworks/search/CloudsSearchDomainClientAdapter.java
> +	public void sendDocuments(String documents){
Take a Document class instead of string

2018-01-15 23:47 UTC, john-hill commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/search/SearchManagerImpl.java
> +						EntityPath path = searchDocumentDriver.getEntityPath(hit.getId());
put path in the search index instead of checking every time. manager creates path in document

2018-01-15 23:47 UTC, john-hill commented on lib/lib-search/src/test/java/org/sagebionetworks/search/CloudSearchDomainClientAdapterTest.java
> +		String exceptionMessage = "Some message";
should directly test the handleException method.

2018-01-15 23:47 UTC, john-hill commented on lib/lib-search/src/main/java/org/sagebionetworks/search/CloudsSearchDomainClientAdapter.java
> +			logger.error("Failed for unexpected reasons with status: " + e.getStatusCode());
either log or throw. wrap the exception (keep the cause) to keep the full stack trace.

2018-01-15 23:47 UTC, john-hill commented on lib/lib-search/src/main/java/org/sagebionetworks/search/CloudsSearchDomainClientAdapter.java
> +			throw e;
return e since return for the rest (be consistent)

2018-01-15 23:47 UTC, john-hill commented on lib/lib-search/src/main/java/org/sagebionetworks/search/SearchUtil.java
> +	static String convertSearchDocumentsToJSONString(List<Document> documents) {
add a test for this.

2018-01-15 23:47 UTC, john-hill commented on lib/lib-search/src/test/java/org/sagebionetworks/search/SearchUtilTest.java
> +
hits test where all of the values are null

2018-01-15 23:47 UTC, john-hill commented on lib/lib-search/src/main/java/org/sagebionetworks/search/SearchUtil.java
> +			throw new DatastoreException("no groups for user " + userInfo);
illegal args if empty.

2018-01-15 23:47 UTC, john-hill commented on lib/lib-auto-generated/src/main/resources/schema/org/sagebionetworks/repo/model/search/Document.json
> +                    "description": "Delete the document from cloudsearch"
camel case

2018-01-15 23:47 UTC, john-hill commented on lib/lib-search/src/main/java/org/sagebionetworks/search/CloudSearchClient.java
> -	private SimpleHttpClient httpClient;
remove SimpleHttpClient  from search-lib pom.xml

2018-01-15 23:47 UTC, john-hill commented on lib/lib-search/src/main/java/org/sagebionetworks/search/CloudSearchClientException.java
>  		super(message);
switch to cause

2018-01-15 23:47 UTC, john-hill commented on services/repository/src/main/java/org/sagebionetworks/repo/web/controller/BaseController.java
> +		IllegalArgumentException ds = new IllegalArgumentException("Invalid request: "+ex.getMessage());
pass cause (not message).

2018-01-15 23:47 UTC, john-hill commented on lib/lib-search/src/main/java/org/sagebionetworks/search/CloudSearchClientProvider.java
> +			throw new SearchDisabledException();
IllegealState("This feature must be enable in production")

2018-01-15 23:47 UTC, john-hill commented on lib/lib-search/src/main/java/org/sagebionetworks/search/CloudSearchClientProvider.java
> +				throw new TemporarilyUnavailableException("Search has not yet been initialized. Please try again later!");
throw or log

2018-01-15 23:47 UTC, john-hill commented on lib/lib-search/src/test/java/org/sagebionetworks/search/CloudSearchClientProviderTest.java
> +		provider.getCloudSearchClient();
try catch if want verify

2018-01-15 23:47 UTC, john-hill commented on lib/lib-search/src/main/java/org/sagebionetworks/search/CloudSearchClientProvider.java
> +	public void initialize() {
If initialize only occurs when a search is run (not on startup), the stack builder can trigger a search to trigger the initialize.  Then we no longer need this "hacky" random sleep.

2018-01-15 23:47 UTC, john-hill commented on lib/lib-search/src/main/java/org/sagebionetworks/search/CloudsSearchDomainClientAdapter.java
> +			return new CloudSearchClientException(statusCode, e.getMessage());
can just used illegal for 400 and original server exception (already mapped to 502)

2018-01-15 23:47 UTC, john-hill commented on lib/lib-search/src/main/java/org/sagebionetworks/search/SearchDisabledException.java
> +
replaced with IllegalState

2018-01-15 23:47 UTC, john-hill commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/search/SearchManagerImpl.java
> +		System.out.println(hits);
remove

2018-01-15 23:47 UTC, john-hill commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/search/SearchManagerImpl.java
> +					// We need to remove this from the hits
single line log (no exception)

2018-01-15 23:47 UTC, john-hill commented on services/repository/src/main/java/org/sagebionetworks/repo/web/controller/SearchController.java
> +			HttpServletRequest request) {
remove request

2018-01-16 02:57 UTC, zimingd commented on lib/lib-search/src/main/java/org/sagebionetworks/search/SearchUtil.java
> +	static String convertSearchDocumentsToJSONString(List<Document> documents) {
tests already existed but It was named differently because I refactored this method's name afterwards.

2018-01-17 03:30 UTC, merged