PLFM-5511
Sage-Bionetworks/Synapse-Repository-Services pull request #3620
Opened 2019-05-31 19:45 UTC by nickgros

Ability to request just administrators or non-administrator members of a team

2019-06-04 01:54 UTC, zimingd requested changes

2019-06-04 01:54 UTC, zimingd commented on integration-test/src/test/java/org/sagebionetworks/IT500SynapseJavaClient.java
> +		// query for team members using name fragment and admin status
these cases should already be covered in the Autowired/unit tests at the manager level. Should only need to test for ability to send a request and get results back at this level

2019-06-04 01:54 UTC, zimingd commented on lib/jdomodels/src/main/java/org/sagebionetworks/repo/model/dbo/dao/DBOTeamDAOImpl.java
> +		param.addValue(LIMIT_PARAM_NAME, limit);
always get list of admin ids, refactor setAdminStatus() to to take that list as a parameter

2019-06-04 01:54 UTC, zimingd commented on lib/jdomodels/src/main/java/org/sagebionetworks/repo/model/dbo/dao/DBOTeamDAOImpl.java
> +				} else {
build up select query instead of choosing one of three select queries

2019-06-04 01:54 UTC, zimingd commented on lib/jdomodels/src/main/java/org/sagebionetworks/repo/model/dbo/principal/PrincipalPrefixDAOImpl.java
> +	public List<Long> listCertainTeamMembersForPrefix(String prefix, Long teamId,
explicit list for inclusions/exclusions instead of boolean determining behavior

2019-06-04 01:54 UTC, zimingd commented on lib/jdomodels/src/main/java/org/sagebionetworks/repo/model/dbo/principal/PrincipalPrefixDAOImpl.java
> +	public List<Long> listCertainTeamMembersForPrefix(String prefix, Long teamId,
you will need to build up a sql query based on the list.

also document exclusions will take precedence over inclusions

2019-06-04 01:54 UTC, zimingd commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/team/TeamManagerImpl.java
> +				teamDAO.getAdminTeamMemberIds(teamId).forEach(id -> adminIds.add(Long.parseLong(id)));
```suggestion
				teamDAO.getAdminTeamMemberIds(teamId).stream().map(Long::parseLong)).collect(Collections.set);
```

2019-06-04 01:54 UTC, zimingd commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/team/TeamManagerImpl.java
> +				teamDAO.getAdminTeamMemberIds(teamId).forEach(id -> adminIds.add(Long.parseLong(id)));
same

2019-06-04 01:54 UTC, zimingd commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/team/TeamManagerImplTest.java
> +		assertEquals(tms, pg.getResults());
verify correct dao method is called

2019-06-04 01:54 UTC, zimingd commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/team/TeamManagerImplTest.java
> +		TeamMember tm = new TeamMember();
helper/ put into before() for setup

2019-06-04 21:06 UTC, nickgros commented on client/synapseJavaClient/src/main/java/org/sagebionetworks/client/SynapseClient.java
> +	PaginatedResults<TeamMember> getTeamMembers(String teamId, String fragment, TeamMemberTypeFilterOptions memberType, long limit, long offset) throws SynapseException;
Note to self: preserve old method signature in addition to new one

2019-06-05 23:06 UTC, nickgros commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/team/TeamManagerImplTest.java
> +		when(mockTeamDAO.getAdminTeamMemberIds(TEAM_ID)).thenReturn(adminIds);
Break into 3 tests

2019-06-05 23:06 UTC, nickgros commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/team/TeamManagerImplTest.java
> +		for (TeamMemberTypeFilterOptions filter : TeamMemberTypeFilterOptions.values()) {
break into 3 tests

2019-06-05 23:07 UTC, zimingd approved these changes

2019-06-05 23:07 UTC, zimingd commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/team/TeamManagerImpl.java
> +				results = teamDAO.getMembersInRange(teamId, adminIds, null, limit, offset);
add documentation to this method stating that isAdmin will not be set at the dao level

2019-06-05 23:07 UTC, merged