PLFM-5604 google cloud storage client code
Sage-Bionetworks/Synapse-Repository-Services pull request #3652
Opened 2019-06-25 23:15 UTC by nickgros

2019-06-26 22:40 UTC, nickgros commented on lib/stackConfiguration/src/main/java/org/sagebionetworks/gcp/DefaultGCPCredentialsProvider.java
> + * A AWSCredentialsProvider that will attempt to load AWS credentials from the
Fix the comment, note the environment var

2019-06-26 23:41 UTC, zimingd requested changes

2019-06-26 23:41 UTC, zimingd commented on lib/stackConfiguration/src/main/java/org/sagebionetworks/gcp/SynapseGCPCredentialsProviderChain.java
> +	private List<CredentialsProvider> credentialsProviders = new LinkedList<>();
pull into constructor

2019-06-26 23:41 UTC, zimingd commented on lib/stackConfiguration/src/main/java/org/sagebionetworks/gcp/SynapseGCPCredentialsProviderChain.java
> +			new SynapseGCPCredentialsProviderChain(new PropertyProviderImpl(), new DefaultGCPCredentialsProvider());
either take all providers in constructor as args or take no args and predefine them in constructor.

2019-06-26 23:41 UTC, zimingd commented on lib/stackConfiguration/src/main/java/org/sagebionetworks/gcp/SynapseGCPCredentialsProviderChain.java
> +		List<String> exceptionMessages = null;
instantiate a linked list

2019-06-26 23:41 UTC, zimingd commented on lib/stackConfiguration/src/main/java/org/sagebionetworks/gcp/SynapseGCPCredentialsProviderChain.java
> +				String message = provider + ": " + e.getMessage();
rename to providerErrorMessage

2019-06-26 23:41 UTC, zimingd commented on lib/stackConfiguration/src/main/java/org/sagebionetworks/gcp/SynapseGoogleCloudStorageClient.java
> +	void deleteObject(String bucketName, String key);
bucket

2019-06-26 23:41 UTC, zimingd commented on lib/stackConfiguration/src/main/java/org/sagebionetworks/gcp/SynapseGoogleCloudStorageClientImpl.java
> +				builder.addSource(part);
addSource(partKeys) is supported

2019-06-26 23:41 UTC, zimingd commented on lib/stackConfiguration/src/main/java/org/sagebionetworks/gcp/SynapseGoogleCloudStorageClientImpl.java
> +		storage.copy(Storage.CopyRequest.newBuilder().setSource(BlobId.of(bucket,oldKey)).setTarget(BlobId.of(bucket,newKey)).build());
space out onto multiple lines

2019-06-26 23:41 UTC, zimingd commented on lib/stackConfiguration/src/main/java/org/sagebionetworks/gcp/SynapseSystemPropertiesGCPCredentialsProvider.java
> +	Properties properties;
make abstract class have a final Properties field and set it in the abstract class's constructors. 
and call super(properties)

2019-06-26 23:41 UTC, zimingd commented on lib/stackConfiguration/src/test/java/org/sagebionetworks/SynapseGoogleCloudStorageClientImplUnitTest.java
> +		verify(mockStorage).signUrl(eq(OBJECT_BLOB_INFO), eq(expirationTime),
remove captors if unused

2019-06-26 23:41 UTC, zimingd commented on lib/stackConfiguration/src/test/java/org/sagebionetworks/SynapseGoogleCloudStorageClientImplUnitTest.java
> +		WriteChannelStub writableByteChannel = new WriteChannelStub();
reanme to TestStubWriteChannel

2019-06-26 23:41 UTC, zimingd commented on lib/stackConfiguration/src/test/java/org/sagebionetworks/SynapseGoogleCloudStorageClientImplUnitTest.java
> +		assertThrows(RuntimeException.class, () -> client.deleteObject(BUCKET_NAME, OBJECT_KEY));
change runtime to another more specific exception type. we usually only use runtime exceptions to wrap checked exceptions that we don't expect to occur

2019-06-26 23:41 UTC, zimingd commented on services/repository/pom.xml
> -					<additionnalDependencies>
this is maven's typo
https://maven.apache.org/components/plugins-archives/maven-javadoc-plugin-2.9.1/examples/additionnal-dependencies.html

2019-06-26 23:41 UTC, zimingd commented on services/repository/pom.xml
> -					<additionnalDependencies>
as a note this is fixed in later versions but upgrading the version breaks the document generation. not sure what causes it, but fixing the typos is more work than a simple version bump

2019-06-28 21:28 UTC, zimingd requested changes

2019-06-28 21:28 UTC, zimingd commented on lib/stackConfiguration/src/main/java/org/sagebionetworks/gcp/SynapseGoogleCloudCredentialsProviderChain.java
>  	private List<CredentialsProvider> credentialsProviders = new LinkedList<>();
move to constructor

2019-06-28 21:28 UTC, zimingd commented on lib/stackConfiguration/src/test/java/org/sagebionetworks/gcp/SynapseGoogleCloudCredentialsProviderChainTest.java
> +
test cases for exception handling

2019-06-28 21:28 UTC, zimingd commented on lib/stackConfiguration/src/test/java/org/sagebionetworks/gcp/SynapseGoogleCloudCredentialsProviderChainTest.java
> +
test singleton instance w/ assertSame()

2019-06-28 21:28 UTC, zimingd commented on lib/stackConfiguration/src/main/java/org/sagebionetworks/gcp/SynapseGoogleCloudCredentialsProviderChain.java
> +	public static SynapseGoogleCloudCredentialsProviderChain getInstance() {
getDefaultChainInstance()

2019-07-01 20:11 UTC, zimingd approved these changes

2019-07-01 20:11 UTC, merged