Plfm 5954
Sage-Bionetworks/Synapse-Repository-Services pull request #3875
Opened 2019-12-20 02:08 UTC by john-hill

2020-01-16 02:59 UTC, zimingd commented on services/workers/src/main/java/org/sagebionetworks/worker/entity/EntityReplicationReconciliationWorker.java
> +	public Set<Long> getContainersToReconcile(IdAndVersion idAndVersion) {
Change to return List<Long>

2020-01-16 02:59 UTC, zimingd commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/table/TableManagerSupport.java
> +	public Long getViewNumber(IdAndVersion table);
getViewStateNumber

2020-01-16 02:59 UTC, zimingd commented on lib/lib-table-cluster/src/main/java/org/sagebionetworks/table/cluster/TableIndexDAOImpl.java
> +			String dropStatusTableDML = SQLUtils.dropTableSQL(tableId, type);
drop if exists

2020-01-16 02:59 UTC, zimingd commented on lib/lib-table-cluster/src/main/java/org/sagebionetworks/table/cluster/TableIndexDAOImpl.java
> +			throw new IllegalArgumentException("The size of the column '"+ listColumn.getName()+ "' is too small." +
maybe not required. handled at a higher level

2020-01-16 02:59 UTC, zimingd commented on lib/lib-table-cluster/src/main/java/org/sagebionetworks/table/cluster/TableIndexDAOImpl.java
> +		NamedParameterJdbcTemplate namedTemplate = new NamedParameterJdbcTemplate(this.template);
Make it an instance variable

2020-01-16 02:59 UTC, zimingd commented on lib/lib-table-cluster/src/test/java/org/sagebionetworks/table/cluster/TableIndexDAOImplTest.java
> +		Set<Long> scope = dtos.stream().map(it -> it.getParentId()).collect(Collectors.toSet());
map(EntityDTO::getParenId)

2020-01-16 02:59 UTC, zimingd commented on lib/lib-table-cluster/src/test/java/org/sagebionetworks/table/cluster/TableIndexDAOImplTest.java
> +		assertTrue(results.isEmpty());
assertEquals(Collections.emptySet(), results)

2020-01-16 02:59 UTC, zimingd commented on lib/lib-table-cluster/src/test/java/org/sagebionetworks/table/cluster/SQLUtilsTest.java
> +		assertEquals("DELETE FROM T999 WHERE ROW_ID >= 0", sql);
remove where clause if we intend to delete everything

2020-01-16 02:59 UTC, zimingd commented on lib/lib-table-cluster/src/main/java/org/sagebionetworks/table/cluster/SQLUtils.java
> +		return "DELETE FROM "+getTableNameForId(tableId, TableType.INDEX)+" WHERE "+ROW_ID+" >= 0";
remove where clause

2020-01-16 02:59 UTC, zimingd commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/table/TableIndexManagerImplTest.java
> +	}
verifyNoMoreInteractions(mockIndexDao)

2020-01-16 02:59 UTC, zimingd commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/table/TableViewManagerImpl.java
> +					break;
return

2020-01-16 02:59 UTC, zimingd commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/table/TableViewManagerImpl.java
> +	public Optional<Boolean> isViewAvailableAndUpToDate(IdAndVersion tableId) throws TableFailedException {
try to move this to test

2020-01-16 20:01 UTC, zimingd requested changes

2020-01-16 20:01 UTC, zimingd commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/table/TableViewManagerImplTest.java
> +		verify(mockTableManagerSupport).tryRunWithTableExclusiveLock(eq(mockProgressCallback), eq(expectedKey),
verify non-exclusive lock was also acquired

2020-01-16 20:01 UTC, zimingd commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/table/TableViewManagerImplTest.java
> +				eq(TableViewManagerImpl.TIMEOUT_SECONDS), any(ProgressingCallable.class));
verify acquiring exclusive lock not called

2020-01-16 20:01 UTC, zimingd commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/table/TableViewManagerImplTest.java
> +		});
assert throw exception is equal to your created one.

2020-01-16 20:01 UTC, zimingd commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/table/TableViewManagerImplTest.java
> +				anySet(), anyList());
verifyNoMoreInteractions(mockTableManagerSupport)

2020-01-16 20:01 UTC, zimingd commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/table/TableViewManagerImplTest.java
> +		verify(mockIndexManager, never()).getOutOfDateRowsForView(any(IdAndVersion.class), anyLong(), anySet(),  anyLong());
verifyNoMoreInteraction and verifyNoInteraction

2020-01-16 20:01 UTC, zimingd commented on lib/jdomodels/src/main/java/org/sagebionetworks/repo/model/dbo/dao/table/TableStatusDAOImpl.java
> +							"SELECT " + COL_TABLE_STATUS_CHANGE_ON + " FROM " + TABLE_STATUS + " WHERE "
template this query since it uses similar structure to the query above

2020-01-16 20:01 UTC, zimingd commented on lib/jdomodels/src/test/java/org/sagebionetworks/repo/model/dbo/dao/table/TableStatusDAOImplTest.java
> +		assertThrows(NotFoundException.class, ()->{
make similar to testGetLastChangedOn_NotFound

2020-01-16 20:01 UTC, zimingd commented on lib/jdomodels/src/test/java/org/sagebionetworks/repo/model/dbo/dao/table/ViewScopeDaoImplTest.java
> +		assertFalse(startEtag.equals(dboType.getEtag()));
assertNotEqual()

2020-01-16 20:01 UTC, zimingd commented on services/workers/src/test/java/org/sagebionetworks/table/worker/TableViewIntegrationTest.java
> +		// Wait for the
finish sentence

2020-01-16 20:01 UTC, zimingd commented on services/workers/src/test/java/org/sagebionetworks/table/worker/TableWorkerIntegrationTest.java
> +	// Multiple values are not currently supported on tables (only supported on views). See: PLFM-6043
block attempts to create a table with LIST columns.

2020-01-16 20:02 UTC, zimingd approved these changes

2020-01-16 20:02 UTC, merged

2020-01-17 01:50 UTC, john-hill commented on lib/lib-table-cluster/src/test/java/org/sagebionetworks/table/cluster/TableIndexDAOImplTest.java
> +		Set<Long> scope = dtos.stream().map(it -> it.getParentId()).collect(Collectors.toSet());
This did not work:  Error:
"The type EntityDTO does not define getParenId(EntityDTO) that is applicable here"
It seems I  would need a static function that takes an EntityDTO and extract the parent Id.

2020-01-17 02:28 UTC, marcomarasca commented on lib/lib-table-cluster/src/test/java/org/sagebionetworks/table/cluster/TableIndexDAOImplTest.java
> +		Set<Long> scope = dtos.stream().map(it -> it.getParentId()).collect(Collectors.toSet());
You are probably missing a t :)

2020-01-17 02:33 UTC, john-hill commented on lib/lib-table-cluster/src/test/java/org/sagebionetworks/table/cluster/TableIndexDAOImplTest.java
> +		Set<Long> scope = dtos.stream().map(it -> it.getParentId()).collect(Collectors.toSet());
Ahhh, that is the ticket!