give better error message when user can't join team due to AR restriction
Sage-Bionetworks/Synapse-Repository-Services pull request #4106
Opened 2020-06-24 22:55 UTC by leem42

2020-06-30 00:51 UTC, brucehoff requested changes
Please review canAddTeamMember().   There are multiple reasons it can return false.  Your message is specific to one of the reasons.  In the proposed code change there are a number of situations in which the message would not correctly describe the reason.

One approach might be to change canAddTeamMember() to include an object having a boolean and a 'reason' string.  For example see org.sagebionetworks.repo.model.auth.AuthorizationStatus()which does something similar.  Then canAddTeamMember() could return an error message customized for the particular situation causing it to return 'false'.

See TeamManagerImplTest for a variety of reasons that canAddTeamMember() would return false.

2020-07-01 18:37 UTC, leem42 commented
@brucehoff Thank you for pointing out those issues, looking at the [AuthorizationStatus](https://github.com/Sage-Bionetworks/Synapse-Repository-Services/blob/e57e8fab8e0ee6329526260684cfb4d02db64188/lib/models/src/main/java/org/sagebionetworks/repo/model/auth/AuthorizationStatus.java) class it looks like I could return that object from the canAddTeamMember since it has a method `isAuthorized` and `getMessage`. Would you also agree with returning AuthorizationStatus from that method?

2020-07-07 17:32 UTC, brucehoff requested changes

2020-07-07 17:32 UTC, brucehoff commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/team/TeamManagerImpl.java
> +	public static final AuthorizationStatus UNAUTHORIZED_ADD_TEAM_MEMBER_UNMET_AR =  AuthorizationStatus.accessDenied(TeamManagerImpl.MSG_CANNOT_ADD_TEAM_MEMBER_UNMET_AR);
you don't need "TeamManagerImpl." on ll. 129, 130

2020-07-07 17:32 UTC, brucehoff commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/team/TeamManagerImpl.java
> +		if (hasUnmetAccessRequirements(principalUserInfo, teamId)) return UNAUTHORIZED_ADD_TEAM_MEMBER_UNMET_AR;
1) Public team and userInfo.equals(principalUserInfo) -> "You can't join the team until you meet the ARs"
2) Private team and the prospective member is calling -> "You can't join the team until you meet the ARs"
3) Private team and the manager is calling AND there's no outstanding request  -> "You can't add them to the team until they've met the ARs and requested to join the team"
4) Private team and the manager is calling AND there's an outstanding request -> UNAUTHORIZED_ADD_TEAM_MEMBER_UNMET_AR

2020-07-07 17:32 UTC, brucehoff commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/team/TeamManagerImpl.java
> +			return openInvitationCount>0L ? AUTHORIZED_ADD_TEAM_MEMBER : UNAUTHORIZED_ADD_TEAM_MEMBER_GENERIC;
"An invitation is required to join the team."

2020-07-07 17:32 UTC, brucehoff commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/team/TeamManagerImpl.java
> +			if (!amTeamAdmin) return UNAUTHORIZED_ADD_TEAM_MEMBER_GENERIC; // can't add someone unless I'm a Team administrator
"You must be a team manager to perform this operation."

2020-07-07 17:32 UTC, brucehoff commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/team/TeamManagerImpl.java
> +			return openRequestCount>0L  ? AUTHORIZED_ADD_TEAM_MEMBER : UNAUTHORIZED_ADD_TEAM_MEMBER_GENERIC;
"The prospective member must request to join the team."

2020-07-07 17:32 UTC, brucehoff commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/team/TeamManagerImpl.java
> +		if (!canAddTeamMemberStatus.isAuthorized()) throw new UnauthorizedException(canAddTeamMemberStatus.getMessage());
canAddTeamMemberStatus.checkAuthorizationOrElseThrow();

2020-07-07 17:32 UTC, brucehoff commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/team/TeamManagerImplTest.java
> +		assertEquals(teamManagerImpl.canAddTeamMember(userInfo, TEAM_ID, userInfo, false), teamManagerImpl.AUTHORIZED_ADD_TEAM_MEMBER);
TeamManagerImpl.AUTHORIZED_ADD_TEAM_MEMBER (18 times)

2020-07-21 17:32 UTC, brucehoff commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/team/TeamManagerImpl.java
> +		if (alreadyInTeam) return AUTHORIZED_ADD_TEAM_MEMBER;
What are the implications of returning 'true' when the member is already in the team?

2020-07-21 17:40 UTC, brucehoff commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/team/TeamManagerImpl.java
> +		if (hasUnmetAccessRequirements(principalUserInfo, teamId)) {
// either (1) principalIsSelf and I have an invitation or (2) principal is other, I am a team admin and there is a membership request

2020-07-21 17:45 UTC, brucehoff commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/team/TeamManagerImpl.java
> +		AuthorizationStatus hasInviteOrRequestToJoin = null;
rename the variable, e.g. to 'canJoin'

2020-07-21 17:45 UTC, brucehoff commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/team/TeamManagerImpl.java
> +		if (team.getCanPublicJoin()!=null && team.getCanPublicJoin()==true) return AUTHORIZED_ADD_TEAM_MEMBER;
use BooleanUtils.isTrue() in apache commons library

2020-07-21 17:46 UTC, brucehoff commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/team/TeamManagerImpl.java
> +			if (userInfo.equals(principalUserInfo)) {
use principalIsSelf

2020-07-21 17:46 UTC, brucehoff commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/team/TeamManagerImpl.java
> -	 * @param principalId the ID of the one to be added to the team
add the method parameters principalUserInfo, alreadyInTeam

2020-07-22 16:56 UTC, brucehoff approved these changes
Looks great!

2020-07-22 16:57 UTC, merged