PLFM-6191: Added support for HAS_LIKE predicate
Sage-Bionetworks/Synapse-Repository-Services pull request #4369
Opened 2021-05-10 23:04 UTC by marcomarasca

2021-05-10 23:53 UTC, williamvietnguyen approved these changes

2021-05-11 19:44 UTC, john-hill requested changes

2021-05-11 19:44 UTC, john-hill commented on lib/lib-table-query/src/main/java/org/sagebionetworks/table/query/model/ArrayHasLikePredicate.java
> +		}
If this project is dependent on guava
Iterables.concat(valuesIterable , your new item);

2021-05-11 19:44 UTC, john-hill commented on lib/lib-table-cluster/src/main/java/org/sagebionetworks/table/cluster/SQLTranslatorUtils.java
> +			case HAS_LIKE:
Maybe a new ColumnMultiValueFunctionQueryFilter with function name and parameters.

2021-05-11 19:44 UTC, john-hill commented on lib/lib-table-cluster/src/test/java/org/sagebionetworks/table/cluster/SQLTranslatorUtilsTest.java
> +	public void testReplaceArrayHasLikePredicate() throws ParseException {
with

2021-05-12 01:04 UTC, john-hill approved these changes

2021-05-12 01:04 UTC, merged