PLFM-6957
Sage-Bionetworks/Synapse-Repository-Services pull request #4524
Opened 2021-11-05 20:36 UTC by xschildw

2021-11-12 22:50 UTC, brucehoff requested changes
Just a couple changes.  Overall it looks great.  I really like your refactor of AccessInterceptorTest.

2021-11-12 22:50 UTC, brucehoff commented on lib/lib-auto-generated/src/main/resources/schema/org/sagebionetworks/repo/model/AuthenticationMethod.json
> +      "description": "TODO: Auto-generated description"
please fill in the descriptions

2021-11-12 22:50 UTC, brucehoff commented on services/repository/src/test/java/org/sagebionetworks/repo/web/AccessInterceptorTest.java
> +		//doReturn("SESSIONTOKEN").when(mockRequest.getHeader("authorizationMethod"));
remove dead code

2021-11-13 04:52 UTC, xschildw commented
Wish I could take credit for that refactor but @marcomarasca guided me through it. I agree it's elegant...

2021-11-13 04:53 UTC, merged