Dev plfm 6676
Sage-Bionetworks/Synapse-Repository-Services pull request #4620
Opened 2022-03-08 05:11 UTC by xschildw

2022-03-08 21:16 UTC, john-hill requested changes

2022-03-08 21:16 UTC, john-hill commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/dataaccess/AccessRequirementManagerImpl.java
>  		for (RestrictableObjectDescriptor rod : toUpdate.getSubjectIds()) {
We need a delta of the current subjects and the updated subjects to capture the case where a subject ID is removed (the main use case).

2022-03-08 21:16 UTC, john-hill commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/dataaccess/AccessRequirementManagerImplUnitTest.java
> +		verify(mockTransactionalMessenger).sendMessageAfterCommit(TEST_ENTITY_ID, ObjectType.ENTITY, ChangeType.UPDATE);
missing case where there are multiple subjects and case where subject is a folder or project.  Will need a test for the delta on update.

2022-03-18 18:08 UTC, xschildw commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/dataaccess/AccessRequirementManagerImplUnitTest.java
> +		// call under test: "0" should all be signaled
Comment is incorrect. In this case we catch the NotFound and return b4 sending msg.

2022-03-18 19:48 UTC, xschildw commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/dataaccess/AccessRequirementManagerImpl.java
> +	private void signalSubjectId(RestrictableObjectDescriptor rod) {
Should not be private to allow for testing

2022-03-18 19:51 UTC, xschildw commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/dataaccess/AccessRequirementManagerImpl.java
> +import java.nio.channels.NotYetBoundException;
Delete

2022-03-21 21:43 UTC, john-hill approved these changes

2022-03-21 21:43 UTC, john-hill commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/dataaccess/AccessRequirementManagerImplAutoWiredTest.java
> +				accessRequirementManager.deleteAccessRequirement(adminUserInfo, ar.getId().toString());
Remove is not needed.

2022-03-21 21:43 UTC, john-hill commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/dataaccess/AccessRequirementManagerImpl.java
> +		signalSubjectIds(new ArrayList<RestrictableObjectDescriptor>(), accessRequirement.getSubjectIds()); // Create == empty currentSibjectIds
Collections.emptyList()

2022-03-21 21:43 UTC, john-hill commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/dataaccess/AccessRequirementManagerImplUnitTest.java
> +		Set<RestrictableObjectDescriptor> subjectIdsToSignal = arm.findSubjectIdsToSignal(currentSubjectIds, updatedSubjectIds);
// call under test

2022-03-21 21:43 UTC, merged