PLFM-7302: Map subject to principal alias when using an oauth provider
Sage-Bionetworks/Synapse-Repository-Services pull request #4694
Opened 2022-07-20 16:43 UTC by marcomarasca

2022-07-20 21:47 UTC, brucehoff commented
TODO:  Add regex to validate provider+subject alias.
TODO:  Add integration test that persists a provider+subject alias.

2022-07-20 21:47 UTC, brucehoff requested changes

2022-07-20 21:47 UTC, brucehoff commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/oauth/GoogleOAuth2Provider.java
> +    private static final String TOKEN_URL = "https://oauth2.googleapis.com/token";
Consider getting `AUTHORIZE_URL`, `TOKEN_URL`, and `GOOGLE_OAUTH_USER_INFO_API_URL` from the Google OIDC discovery document:  from https://accounts.google.com/.well-known/openid-configuration

2022-07-20 21:47 UTC, brucehoff commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/oauth/GoogleOAuth2Provider.java
> +	public static final String VERIFIED_EMAIL = "email_verified";
VERIFIED_EMAIL -> VERIFIED_EMAIL

2022-07-20 21:47 UTC, brucehoff commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/UserManagerImpl.java
> +		PrincipalAlias pa = this.principalAliasDAO.findPrincipalWithAlias(getAliasForOauthProvider(provider, subject), AliasType.USER_OAUTH);
PrincipalAlias pa = this.principalAliasDAO.findPrincipalWithAlias(oauthAlias, AliasType.USER_OAUTH);

2022-07-20 21:47 UTC, brucehoff commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/UserManagerImpl.java
> +		return provider.name() + " " + subject;
Note that the 'alias unique' shouldn't change the OIDC alias *at all*.

2022-07-25 18:59 UTC, john-hill requested changes

2022-07-25 18:59 UTC, john-hill commented on lib/jdomodels/src/main/resources/schema/PrincipalOIDCBinding-ddl.sql
> +  `SUBJECT` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
the spec says ascii.

2022-07-25 18:59 UTC, john-hill commented on lib/jdomodels/src/test/java/org/sagebionetworks/repo/model/dbo/principal/PrincipalOIDCBindingDaoImplTest.java
> +			dao.bindPrincipalToSubject(principalId, OAuthProvider.GOOGLE_OAUTH_2_0, subject);
this should be noop

2022-07-25 18:59 UTC, john-hill commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/UserManagerImpl.java
> +				throw new NameConflictException("A user is already bound to the '" + user.getOauthProvider() +"' provider with the same identity");
Have you already used this 'google' account to log into another Synapse account?

2022-07-25 18:59 UTC, john-hill commented on services/repository-managers/src/main/resources/private/managers-spb.xml
> +		<constructor-arg>
can we move out of the xml, using annotations.

2022-07-25 23:27 UTC, john-hill approved these changes

2022-07-25 23:28 UTC, merged