PLFM-7322: added ability to use CRC32() in query language
Sage-Bionetworks/Synapse-Repository-Services pull request #4702
Opened 2022-07-29 16:06 UTC by harveyx22

2022-07-29 21:04 UTC, john-hill approved these changes

2022-07-29 22:03 UTC, marcomarasca requested changes
Please add an integration test to make sure that the SQL query is actually executed, See TableWorkerIntegrationTest

2022-07-29 22:04 UTC, marcomarasca commented on lib/lib-javadoc/src/main/resources/SQLSpecification2.csv
> +Numeric Functions,"Perform a checksum calculation using the salt, tag, id, and benefactorId to detect if changed have been made to the data.","select sum(crc32(concat('salt','-',etag,'-',id,'-',benef
The description should be generic for the CRC32 function. E.g. Perform a checksum calculation of a list of columns.

2022-08-08 19:08 UTC, marcomarasca approved these changes

2022-08-08 19:08 UTC, merged