Plfm 7377.1
Sage-Bionetworks/Synapse-Repository-Services pull request #4713
Opened 2022-08-26 18:04 UTC by SandhraSokhal

2022-08-27 00:15 UTC, marcomarasca requested changes

2022-08-27 00:15 UTC, marcomarasca commented on lib/models/src/main/java/org/sagebionetworks/repo/model/drs/AccessId.java
> +        return AccessIdParser.parseAccessId(toParse);
Consider simplifying this to just a toParse.split(separator), then use the FileHandleAssociateType to get the type and the IdAndVersion to parse the synId (if the version is not there throw an exception). Finally the id of a file handle can be parsed using Long.parse.

2022-08-27 00:15 UTC, marcomarasca commented on lib/models/src/main/java/org/sagebionetworks/repo/model/drs/AccessId.java
> +        if (synapseIdWithVersion == null || associateType == null || fileHandleId == null) {
This should be moved to the build() in the builder, the constructor should be private and the builder should be part of this class with a method to return an ionstance of the builder.

2022-08-27 00:15 UTC, marcomarasca commented on lib/models/src/main/java/org/sagebionetworks/repo/model/drs/AccessIdBuilder.java
> +        return new AccessId(associateType, synapseIdWithVersion, fileHandleId);
ValidateArgument.required(associateType), etc

2022-08-27 00:15 UTC, marcomarasca commented on lib/models/src/main/java/org/sagebionetworks/repo/model/drs/AccessId.java
> +    public static AccessId parse(String toParse) {
Let us have two method: encode and rename this to decode

2022-08-27 00:15 UTC, marcomarasca commented on lib/models/src/main/java/org/sagebionetworks/repo/model/drs/AccessId.java
> +    final String synapseIdWithVersion;
Consider using IdAndVersion

2022-08-27 00:15 UTC, marcomarasca commented on lib/models/src/test/java/org/sagebionetworks/repo/model/drs/AccessIdParserTest.java
> +import org.junit.Test;
PLease use junit 5 instead

2022-08-27 00:15 UTC, marcomarasca commented on lib/models/src/test/java/org/sagebionetworks/repo/model/drs/AccessIdParserTest.java
> +        try {
assertThrows from Junit 5

2022-08-27 00:15 UTC, marcomarasca commented on lib/models/src/test/java/org/sagebionetworks/repo/model/drs/AccessIdTest.java
> +import org.junit.Test;
PLease use Junit 5

2022-08-27 00:15 UTC, marcomarasca commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/drs/DrsManagerImpl.java
> +        final String drsURI = DRS + "://" + REGISTERED_HOSTNAME + "/";
Can this be a constant?

2022-08-27 00:15 UTC, marcomarasca commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/drs/DrsManager.java
> +    DrsObject getDrsObject(Long userId, String id, Boolean expand) throws NotFoundException, DatastoreException,
Can expand be null?

2022-08-27 00:15 UTC, marcomarasca commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/drs/DrsManagerImpl.java
> +            result.setVersion(dataset.getVersionLabel());
isn't it the version of the dataset?

2022-08-27 00:15 UTC, marcomarasca commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/drs/DrsManagerImpl.java
> +            dataset.getItems().forEach(entityRef -> {
getItems() might be null

2022-08-27 00:15 UTC, marcomarasca commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/drs/DrsManagerImpl.java
> +                final String fileIdWithVersion = entityRef.getEntityId() + "." + entityRef.getVersionNumber();
You might want to reuse the IdAndVersion to make sure the returned id is consistent.

2022-08-27 00:15 UTC, marcomarasca commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/drs/DrsManagerImplUnitTest.java
> +        final DrsObject drsObject = drsManager.getDrsObject(USER_ID, dataset.getId() + "." + ENTITY_VERSION, false);
assertEquals(expectedObject, drsObject)

2022-08-27 00:15 UTC, marcomarasca commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/drs/DrsManagerImplUnitTest.java
> +            verify(entityManager).getEntityForVersion(userInfo, "1", ENTITY_VERSION, null);
verify go outside of the lambda

2022-08-27 00:15 UTC, marcomarasca commented on integration-test/src/test/java/org/sagebionetworks/ITDrsControllerTest.java
> +        this.fileEntityUtil = new FileDataCreationUtil(adminSynapse, synapse);
Consider removing this additional utility, this is specific for this test.

2022-08-30 22:01 UTC, john-hill approved these changes

2022-08-30 22:01 UTC, john-hill commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/drs/DrsManagerImpl.java
> +    private void validateIdStartWithSyn(final String id) {
you can keep this but, it is not strictly necessary.

2022-08-30 22:01 UTC, john-hill commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/drs/DrsManagerImpl.java
> +            result.setVersion(dataset.getVersionNumber() != null ? dataset.getVersionNumber().toString() : "1");
The version should already match the input version.  If it did not match then something went super wrong in the entity manager code.

2022-08-30 22:01 UTC, john-hill commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/drs/DrsManagerImpl.java
> +            if (CollectionUtils.isNotEmpty(dataset.getItems())) {
A simple null check would give the exact same results.

2022-08-30 22:01 UTC, john-hill commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/drs/DrsManagerImpl.java
> +        if (!id.startsWith("syn")) {
KeyFactory.idAndVersion(ref.getId(), ref.getVersion())

2022-08-30 22:01 UTC, john-hill commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/drs/DrsManagerImpl.java
>              final FileEntity file = (FileEntity) entity;
suggest two (no private) methods to build either a file or dataset DrsObject, with unit testing of both methods.

2022-08-30 22:01 UTC, john-hill commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/drs/DrsManagerImplUnitTest.java
> +        drsObject.setId(expectedFile.getId() + "." + "1");
the version should be from expectedFileEntity

2022-08-30 22:01 UTC, john-hill commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/drs/DrsManagerImplUnitTest.java
> +        final String idAndVersion = expectedDataset.getId() + "." + 1;
version from the dataset.

2022-08-30 22:01 UTC, john-hill commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/drs/DrsManagerImplUnitTest.java
> +                idAndVersion + "_" + expectedFile.getDataFileHandleId());
Can this use your AccessId or the raw string.

2022-08-30 22:01 UTC, john-hill commented on integration-test/src/test/java/org/sagebionetworks/ITDrsControllerTest.java
> +        drsObject.setVersion(expectedDataset.getVersionComment());
This should check the version number.

2022-08-30 22:01 UTC, john-hill commented on lib/models/src/main/java/org/sagebionetworks/repo/model/drs/AccessId.java
> +    private AccessId(final AccessIdBuilder accessIdBuilder) {
Builder should call the new AccessId(all params);

2022-08-30 22:01 UTC, john-hill commented on lib/models/src/main/java/org/sagebionetworks/repo/model/drs/AccessId.java
> +        if (!synIdWithVersion.startsWith("syn")) {
syn check not needed.

2022-08-30 22:01 UTC, john-hill commented on lib/models/src/main/java/org/sagebionetworks/repo/model/drs/AccessId.java
> +    public static String encode(final AccessId accessId) {
should be able to call encode on the actual object.

2022-08-30 22:01 UTC, john-hill commented on lib/models/src/main/java/org/sagebionetworks/repo/model/drs/AccessId.java
> +        return accessId.associateType.name() + DELIMITER +
StringJoiner or String.format.  + idAndVersion.toString() will give that part correctly.

2022-08-30 22:01 UTC, john-hill commented on lib/models/src/main/java/org/sagebionetworks/repo/model/drs/AccessId.java
> +    public static class AccessIdBuilder {
rename->Builder
obj = new AccessId(foo, bar, foobar);
obj = AccessId.builder().setFileHandle(foo).setIdAndVersions(bar).setType(foobar).build();

2022-08-30 22:01 UTC, john-hill commented on lib/models/src/main/java/org/sagebionetworks/repo/model/drs/AccessId.java
> +            return new AccessId(this);
I would pass the three args rather than the builder.

2022-08-30 22:01 UTC, john-hill commented on lib/models/src/test/java/org/sagebionetworks/repo/model/drs/AccessIdTest.java
> +    public void testEquals() {
not needed because you did not write the equals method.

2022-08-30 22:01 UTC, john-hill approved these changes

2022-08-30 22:02 UTC, marcomarasca approved these changes

2022-08-30 22:03 UTC, merged