PLFM-6275
Sage-Bionetworks/Synapse-Repository-Services pull request #4726
Opened 2022-09-08 16:21 UTC by nickgros

- Add 'additionalFilters' to TransformSqlWithFacetsRequest object
- Support transforming QueryFilters to Synapse SQL
- Refactor to reuse less complex code

Draft while pending API design review

2022-09-08 19:31 UTC, nickgros commented on lib/lib-table-query/src/main/java/org/sagebionetworks/table/query/util/FacetUtils.java
> +				.collect(Collectors.joining(" AND "));
IMO this is much more clear than the imperative style loop

2022-09-08 19:31 UTC, nickgros commented on lib/lib-table-query/src/main/java/org/sagebionetworks/table/query/util/FacetUtils.java
> -			if(columNameToIgnore == null || !facetColumn.getColumnName().equals(columNameToIgnore)){ //make sure not to include the ignored column
`columnNameToIgnore` is now filtered in `concatFacetSearchConditionStrings`

2022-09-13 20:06 UTC, john-hill requested changes
We think this would be easier and cleaner to implement as an extension of the bundle.

2022-09-13 20:06 UTC, john-hill commented on lib/lib-table-query/src/main/java/org/sagebionetworks/table/query/util/FacetUtils.java
> +	public static String concatFacetSearchConditionStrings(List<FacetRequestColumnModel> validatedFacets, Optional<String> columNameToIgnore){
Cannot have Optional as method param
Can overload the signature.
In method can use
Name valueOption = Optional.ofNullable(param)

2022-09-13 20:06 UTC, john-hill commented on lib/lib-table-query/src/main/java/org/sagebionetworks/table/query/util/FacetUtils.java
> +	private static String concatConditionStrings(List<String> conditionStrings) {
This means there is no unit test for this.

2022-09-13 20:06 UTC, john-hill commented on lib/lib-table-query/src/main/java/org/sagebionetworks/table/query/util/FacetUtils.java
> +		List<String> conditionStrings = facetColumnsWithoutIgnoredColumn.stream().map(FacetRequestColumnModel::getSearchConditionString).collect(Collectors.toList());
can this be a single line stream with a single line filter.

2022-09-13 20:06 UTC, john-hill commented on lib/lib-table-query/src/main/java/org/sagebionetworks/table/query/util/FacetUtils.java
> +		List<String> conditionStrings = facetColumnsWithoutIgnoredColumn.stream().map(FacetRequestColumnModel::getSearchConditionString).collect(Collectors.toList());
...filter(Not(facet.getColumnName().equal(columNameToIgnore)))

2022-09-13 20:06 UTC, john-hill commented on lib/lib-table-query/src/main/java/org/sagebionetworks/table/query/util/FacetUtils.java
> +		if (filter instanceof ColumnSingleValueQueryFilter) {
Find a way to move this logic out of a static util and into a PoJo with methods like toSql().

2022-12-03 01:20 UTC, closed without merging

2022-12-03 01:20 UTC, john-hill commented
We went another route