PLFM-7395
Sage-Bionetworks/Synapse-Repository-Services pull request #4735
Opened 2022-09-14 22:59 UTC by SandhraSokhal

2022-09-15 17:39 UTC, SandhraSokhal commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/EntityManagerImplAutowireTest.java
> +		assertEquals("[\"\"]", projectJSON.get("key").toString());
this should return empty string instead of array having empty string

2022-09-15 17:41 UTC, SandhraSokhal commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/EntityManagerImplAutowireTest.java
> +		assertEquals("[\"\"]", projectJSON.get("key").toString());
should return empty string

2022-09-15 17:42 UTC, SandhraSokhal commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/EntityManagerImplAutowireTest.java
> +		assertEquals("[\"test\"]", projectJSON.get("key").toString());
should be single value

2022-09-15 17:42 UTC, SandhraSokhal commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/EntityManagerImplAutowireTest.java
> +		assertEquals("[\"one\"]", projectJSON.get("key").toString());
single string

2022-09-15 18:00 UTC, SandhraSokhal commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/EntityManagerImplAutowireTest.java
> +		assertEquals("[\"\"]", projectJSON.get("key").toString());
should be empty string

2022-09-15 18:01 UTC, SandhraSokhal commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/EntityManagerImplAutowireTest.java
> +		assertEquals("[\"\"]", projectJSON.get("key").toString());
empty string

2022-09-15 18:04 UTC, SandhraSokhal commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/EntityManagerImplAutowireTest.java
> +		toUpdate.put("key", List.of("", "1"));
Need to check , what if 1 is needed to pass as string in case ID's

2022-09-15 18:08 UTC, SandhraSokhal commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/EntityManagerImplAutowireTest.java
> +		assertEquals("a value type must be set for values associated with key=key", assertThrows(IllegalArgumentException.class, () -> {
error message should be changed

2022-09-15 18:11 UTC, SandhraSokhal commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/EntityManagerImplAutowireTest.java
> +		assertEquals("[\"null\"]", updateEntityJson.get("key").toString());
single value should be returned

2022-09-15 18:11 UTC, SandhraSokhal commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/EntityManagerImplAutowireTest.java
> +		assertEquals("[\"null\"]", toUpdate.get("key").toString());
single value should be returned

2022-09-15 18:25 UTC, SandhraSokhal commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/EntityManagerImplAutowireTest.java
> +        toUpdate.put("key", JSONObject.NULL);
should throw error

2022-09-15 18:28 UTC, SandhraSokhal commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/EntityManagerImplAutowireTest.java
> +        toUpdate.put("key", JSONObject.NULL);
should throe an error

2022-09-20 18:37 UTC, john-hill requested changes

2022-09-20 18:37 UTC, john-hill commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/schema/AnnotationsTranslatorImpl.java
> +			Object object = jsonObject.get(key);
going to try and do a simple instance of Boolean.

2022-09-20 18:37 UTC, john-hill commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/EntityManagerImplAutowireTest.java
> +
test case:
We have a schema but the annotation key is not in the schema.  For that case, it should be treated as if schema did not exist.

2022-09-20 18:37 UTC, john-hill commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/schema/AnnotationsTranslatorImpl.java
> +		} else if (value.getValue().size() == 1 && isSingleMap.isEmpty()) {
This logic will change with the addition of the new test.

Need a more complex map.  Map<Key, Enum> Where enum {SINGLE, ARRAY, NOT_DEFINED}
map.getOrElse(NOT_DEFINED);
Logic:
not_defined = Same as no schema case.
single = must be a single
array = must be an array

2022-09-20 18:37 UTC, john-hill commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/EntityManagerImplAutowireTest.java
> +		organization = jsonSchemaManager.createOrganziation(adminUserInfo, createdOrganizationRequest);
organization setup can be moved to the setup function

2022-09-20 23:11 UTC, john-hill approved these changes
Looks good! Feel free to merge if the build passes.

2022-09-21 04:02 UTC, merged