Adding dataset default column to dataset collection
Sage-Bionetworks/Synapse-Repository-Services pull request #4769
Opened 2022-11-09 16:49 UTC by SandhraSokhal

2022-11-10 00:18 UTC, john-hill commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/table/metadata/providers/Constants.java
>  	static final ObjectField[] DATASET_DEFAULT_COLUMNS = new ObjectField[]{
DATASET_DEFAULT_COLUMNS  -> DATASET_SPECIFIC_COLUMNS

Also rename the FILE_DEFAULT_COLUMNS -> FILE_SPECIFIC_COLUMNS
Remove from the files everything that is in default.

2022-11-10 00:30 UTC, john-hill approved these changes

2022-11-11 23:04 UTC, marcomarasca requested changes
An empty dataset (with an empty set of items) should return 0 as count and size

2022-11-11 23:04 UTC, marcomarasca commented on services/workers/src/test/java/org/sagebionetworks/table/worker/DatasetCollectionIntegrationTest.java
>  		datasetMD5 = defaultColumnMapper.getColumnModels(ViewObjectType.DATASET_COLLECTION,ObjectField.datasetMD5Hex).get(0);
Since now we use all the default columns this specific columns can be removed

2022-11-11 23:35 UTC, marcomarasca approved these changes

2022-11-12 05:24 UTC, merged