PLFM-7719: Stream node snapshots to kinesis
Sage-Bionetworks/Synapse-Repository-Services pull request #4826
Opened 2023-03-27 23:15 UTC by marcomarasca

2023-03-27 23:15 UTC, marcomarasca commented
depends on https://github.com/Sage-Bionetworks/Synapse-Stack-Builder/pull/522

2023-03-30 19:03 UTC, SandhraSokhal requested changes

2023-03-30 19:03 UTC, SandhraSokhal commented on services/workers/src/main/java/org/sagebionetworks/snapshot/workers/writers/NodeObjectRecordWriter.java
> +			boolean logToKinesis = message.getTimestamp().toInstant().isAfter(Instant.now().minus(Duration.ofDays(KINISIS_LOG_MAX_CHANGE_LIFE_DAYS)));
duplicate are fine

2023-03-30 19:03 UTC, SandhraSokhal commented on services/workers/src/main/java/org/sagebionetworks/snapshot/workers/KinesisObjectSnapshotRecord.java
> +	private Long timestamp;
There should be 2 timestamps 1. timestamp of change message 2. timestamp of when the snapshot was taken.

2023-04-05 21:12 UTC, SandhraSokhal approved these changes

2023-04-05 21:14 UTC, merged