PLFM-7799: Keep materialized view available while re-building
Sage-Bionetworks/Synapse-Repository-Services pull request #4851
Opened 2023-05-26 21:48 UTC by marcomarasca

2023-06-01 19:07 UTC, john-hill requested changes

2023-06-01 19:07 UTC, john-hill commented on lib/lib-table-cluster/src/main/java/org/sagebionetworks/table/cluster/TableIndexDAOImpl.java
> +	public int dropStaleTableIndices() {
if we remain the to the temp index, drops will occur automatically. (we can even drop it after the exclusive lock is released).

2023-06-01 19:07 UTC, john-hill commented on lib/lib-table-cluster/src/test/java/org/sagebionetworks/table/cluster/SQLUtilsTest.java
> -				" DROP FOREIGN KEY T999_INDEX_C21__FK," +
we do not need to drop and recreate the FK since we are using _ibfk_

2023-06-01 19:07 UTC, john-hill commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/table/MaterializedViewManagerImpl.java
> +			LockContext parentContext = new LockContext(ContextType.UpdatingMaterializedView, temporaryId);
I would use the real ID as the user might see it and be confused.

2023-06-01 19:07 UTC, john-hill commented on services/repository-managers/src/main/java/org/sagebionetworks/repo/manager/table/MaterializedViewManagerImpl.java
> +		boolean recoverOnLockUnavailable = true;
no longer need this boolean

2023-06-01 19:07 UTC, john-hill commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/table/MaterializedViewManagerImplTest.java
> +		verifyNoMoreInteractions(mockTableManagerSupport);
no more on->indexmanger

2023-06-01 19:07 UTC, john-hill commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/table/MaterializedViewManagerImplTest.java
> +		verifyNoMoreInteractions(mockTableManagerSupport);
no more on index

2023-06-01 19:07 UTC, john-hill commented on services/repository-managers/src/test/java/org/sagebionetworks/repo/manager/table/MaterializedViewManagerImplTest.java
> +	public void testRebuildAvailableViewHoldingTemporaryExclusiveLockWithExclusiveLockNonAvailable() throws Exception {
this should not happen

2023-06-01 21:54 UTC, marcomarasca commented on lib/lib-table-cluster/src/test/java/org/sagebionetworks/table/cluster/SQLUtilsTest.java
> -				" DROP FOREIGN KEY T999_INDEX_C21__FK," +
I tried getting rid of this, but MySQL spits out an error revolving around "in place" vs "copy" algorithm due to the automatic rename of the FK. I think we cannot mix the alter table with a column rename and the table rename at the same time without dropping the FK.

2023-06-02 19:28 UTC, john-hill approved these changes

2023-06-02 19:29 UTC, john-hill approved these changes

2023-06-02 20:21 UTC, merged