Plfm 8242.2
Sage-Bionetworks/Synapse-Repository-Services pull request #5056
Opened 2024-04-05 23:09 UTC by john-hill

2024-04-08 19:04 UTC, marcomarasca requested changes

2024-04-08 19:04 UTC, marcomarasca commented on lib/jdomodels/src/main/java/org/sagebionetworks/repo/model/dbo/file/part/AsyncMultipartUploadComposerDAO.java
> +public interface AsyncMultipartUploadComposerDAO {
GooglePartRangeDao?

2024-04-08 19:04 UTC, marcomarasca commented on lib/jdomodels/src/main/java/org/sagebionetworks/repo/model/dbo/file/part/AsyncMultipartUploadComposerDAO.java
> +	void addPart(String uploadId, PartRange part);
addPartRange?

2024-04-08 19:04 UTC, marcomarasca commented on lib/jdomodels/src/main/java/org/sagebionetworks/repo/model/dbo/file/part/AsyncMultipartUploadComposerDAO.java
> +	boolean doesExist(String uploadId, PartRange part);
doesPartRangeExist

2024-04-08 19:04 UTC, marcomarasca commented on lib/jdomodels/src/main/java/org/sagebionetworks/repo/model/dbo/file/part/AsyncMultipartUploadComposerDAO.java
> +package org.sagebionetworks.repo.model.dbo.file.part;
Should probably liove under a "google" package

2024-04-08 19:04 UTC, marcomarasca commented on lib/jdomodels/src/main/java/org/sagebionetworks/repo/model/dbo/file/part/AsyncMultipartUploadComposerDAOImpl.java
> +		Arrays.stream(toLock).forEach(p -> validatePartRange(p));
You can merge validation with the mapping, validation being just another step in the stream processing

2024-04-08 19:04 UTC, marcomarasca commented on lib/jdomodels/src/test/java/org/sagebionetworks/repo/model/dbo/file/part/AsyncMultipartUploadComposerDAOImplTest.java
> +	public void testFindContiguousPartsWithOrderBy() {
without?

2024-04-08 19:04 UTC, marcomarasca commented on lib/jdomodels/src/test/java/org/sagebionetworks/repo/model/dbo/file/part/AsyncMultipartUploadComposerDAOImplTest.java
> +			assertTrue(asyncDAO.attemptToLockParts(uploadIdOne, (p2) -> {
maybe put this in a new tx

2024-04-08 19:04 UTC, marcomarasca commented on lib/lib-auto-generated/src/main/resources/schema/org/sagebionetworks/repo/model/feature/Feature.json
> +	    	"name": "DISABLE_ASYNC_GOOGLE_MULTIPART_UPLOAD",
-> NEW_GOOGLE_MP_UPLOAD. Any feature is enabled by default.

2024-04-08 19:04 UTC, marcomarasca commented on lib/lib-upload/src/main/java/org/sagebionetworks/upload/multipart/AsyncGoogleMultipartUploadDAO.java
> +public class AsyncGoogleMultipartUploadDAO implements CloudServiceMultipartUploadDAO {
Impl?

2024-04-08 19:04 UTC, marcomarasca commented on lib/lib-upload/src/main/java/org/sagebionetworks/upload/multipart/AsyncGoogleMultipartUploadDAO.java
> +			asyncDAO.attemptToLockParts(request.getUploadId(), con -> {
This can be just an if statement

2024-04-08 19:04 UTC, marcomarasca commented on lib/lib-upload/src/main/java/org/sagebionetworks/upload/multipart/AsyncGoogleMultipartUploadDAO.java
> +		googleCloudStorageClient.composeObjects(bucket, newPartKey, startingPartKeys);
This can break a whole download is by any chance multiple parts are compoesed in a single transaction and one of them fail

2024-04-08 19:04 UTC, marcomarasca commented on lib/lib-upload/src/main/java/org/sagebionetworks/upload/multipart/AsyncGoogleMultipartUploadDAO.java
> +		} while (optional.isPresent());
we need a sageguard around a potential infinite loop, maybe a counter up to the numberOfParts?

2024-04-08 19:04 UTC, marcomarasca commented on lib/lib-upload/src/main/java/org/sagebionetworks/upload/multipart/AsyncGoogleMultipartUploadDAO.java
> +		googleCloudStorageClient.getObjects(request.getBucket(), request.getKey() + "/").forEach(Blob::delete);
this line can be at line 175

2024-04-09 18:23 UTC, SandhraSokhal approved these changes
LGTM

2024-04-09 19:00 UTC, merged